components {
  id: "ball"
  component: "/ball.script"
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 0.8\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"ball\"\n"
  "mask: \"can\"\n"
  "mask: \"table\"\n"
  "mask: \"floor\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "    id: \"sphere\"\n"
  "  }\n"
  "  data: 0.15\n"
  "}\n"
  ""
}
embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/assets/ball.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"default\"\n"
  "  material: \"/builtins/materials/model.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/assets/ball.png\"\n"
  "  }\n"
  "}\n"
  ""
}
