components {
  id: "can"
  component: "/targets/can.script"
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 0.3\n"
  "friction: 0.5\n"
  "restitution: 0.1\n"
  "group: \"can\"\n"
  "mask: \"floor\"\n"
  "mask: \"table\"\n"
  "mask: \"can\"\n"
  "mask: \"ball\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"box\"\n"
  "  }\n"
  "  data: 0.15\n"
  "  data: 0.3\n"
  "  data: 0.15\n"
  "}\n"
  "linear_damping: 0.5\n"
  "angular_damping: 0.5\n"
  ""
}
